# Generated by Django 2.2 on 2019-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=99999999),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(max_length=120),
        ),
    ]
