# Generated by Django 2.2 on 2019-04-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0005_produkty_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Kategoria'),
        ),
    ]
