# Generated by Django 2.2 on 2019-04-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0006_produkty_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='komentaż',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Comment'),
        ),
    ]
