# Generated by Django 2.2 on 2019-04-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0008_produkty_tagi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='komentaż',
        ),
        migrations.AddField(
            model_name='comment',
            name='produkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Produkty'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='tagi',
            field=models.ManyToManyField(blank=True, null=True, to='produkty.Tagi'),
        ),
    ]
