# Generated by Django 2.2 on 2019-04-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0009_auto_20190416_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='produkt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Produkty'),
        ),
    ]
