# Generated by Django 2.2 on 2019-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0012_produkty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='image',
            field=models.FileField(blank=True, upload_to='produkty/image'),
        ),
    ]
