# Generated by Django 2.2 on 2019-05-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0017_auto_20190427_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentaż', 'verbose_name_plural': 'Komentaże'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategria', 'verbose_name_plural': 'Kategrie'},
        ),
        migrations.AlterModelOptions(
            name='producent',
            options={'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='tagi',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
    ]
